config/routes.rb
BlogPerf::Application.routes.draw do
  get "log_out" => "user_sessions#destroy", :as => "log_out"
  get "log_in" => "user_sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "home#index"
  resources :users
  resources :user_sessions
  resources :home
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to home_index_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, notice: 'Signed up!'
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_blogs.html.haml
.row-fluid
  Test blogs list

app/views/home/_messages.html.haml
.row-fluid
  Test messages

app/views/home/index.html.haml
%ul.nav.nav-tabs{ role: 'tablist' }
  %li.active
    = link_to 'BLoGS', '#blogs', { role: 'tab', data: { toggle: 'tab' } }
  %li
    = link_to 'Messages', '#messages', { role: 'tab', data: { toggle: 'tab' } }
  %li
    = link_to 'Settings', '#settings', { role: 'tab', data: { toggle: 'tab' } }
.tab-content
  .tab-pane.active#blogs
    = render 'blogs', locals: { blogs: @blogs }
  .tab-pane#messages
    = render 'messages', locals: { messages: @messages }
  .tab-pane#settings
    = render 'settings', locals: { settings: @settings }

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title BlogPerf
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .content
      = render 'shared/header'
      = yield
      = render 'shared/footer'

app/views/shared/_header.html.haml
.row-fluid
  - if current_user
    .span6.offset6
      Logged in as #{current_user.email}.
      \#{ link_to "Log out", log_out_path }
  - else
    = link_to "Sign up", sign_up_path
    or
    \#{ link_to "log in", log_in_path }
- flash.each do |name, msg|
  = content_tag :div, msg, id: "flash_#{name}"

app/views/user_sessions/new.html.haml
%h1 Log in
= form_tag user_sessions_path do
  %p
    = label_tag :email
    %br
    = text_field_tag :email, params[:email]
  %p
    = label_tag :password
    %br
    = password_field_tag :password
  %p.button= submit_tag "Log in"

app/views/users/new.html.haml
%h1 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %p
    = f.label :email
    %br
    = f.text_field :email
  %p
    = f.label :password
    %br
    = f.password_field :password
  %p
    = f.label :password_confirmation
    %br
    = f.password_field :password_confirmation
  %p.button= f.submit